### ISSUE TITLE
Docker image problem

### ISSUE THREAD

**Issue by abusquets** [hsk81/notex#42]
Hi Hasan,
I would like test your aplication but I have a problem after 

docker build -rm -t hsk81/notex:run .

The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: g++ (>= 4:4.4.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by hsk81** [comment]
Hi Alexander, thank you for the feedback: I'll have a look at it.

**Comment by abusquets** [comment]
I solved.
It was a dns problem.
Thanks
